include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

  errors:
    no_runtimetype_tostring: ignore
    todo: ignore

  exclude:
    # ignore warnings in files from json_serializable, built_value and most generators
    - "**/*.g.dart"

linter:
  rules:
    always_declare_return_types: false
    annotate_overrides: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_catching_errors: false
    avoid_dynamic_calls: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_escaping_inner_quotes: false
    avoid_field_initializers_in_const_classes: false
    avoid_function_literals_in_foreach_calls: false
    avoid_implementing_value_types: false
    avoid_multiple_declarations_per_line: false
    avoid_renaming_method_parameters: false
    avoid_returning_null_for_void: false
    avoid_single_cascade_in_expression_statements: false
    avoid_slow_async_io: false
    avoid_unnecessary_containers: false
    avoid_unused_constructor_parameters: false
    avoid_void_async: false
    await_only_futures: false
    cast_nullable_to_non_nullable: false
    close_sinks: false
    comment_references: false
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    dangling_library_doc_comments: false
    depend_on_referenced_packages: false
    directives_ordering: false
    discarded_futures: false
    do_not_use_environment: false
    empty_catches: false
    file_names: false
    flutter_style_todos: false
    implementation_imports: false
    join_return_with_assignment: false
    leading_newlines_in_multiline_strings: false
    library_prefixes: false
    library_private_types_in_public_api: false
    missing_whitespace_between_adjacent_strings: false
    no_default_cases: false
    no_leading_underscores_for_local_identifiers: false
    no_logic_in_create_state: false
    non_constant_identifier_names: false
    noop_primitive_operations: false
    null_check_on_nullable_type_parameter: false
    one_member_abstracts: false
    overridden_fields: false
    parameter_assignments: false
    prefer_asserts_in_initializer_lists: false
    prefer_asserts_with_message: false
    prefer_conditional_assignment: false
    prefer_contains: false
    prefer_equal_for_default_values: false
    prefer_final_in_for_each: false
    prefer_final_locals: false
    prefer_function_declarations_over_variables: false
    prefer_if_elements_to_conditional_expressions: false
    prefer_if_null_operators: false
    prefer_initializing_formals: false
    prefer_interpolation_to_compose_strings: false
    prefer_is_empty: false
    prefer_is_not_empty: false
    prefer_is_not_operator: false
    prefer_mixin: false
    prefer_null_aware_method_calls: false
    prefer_relative_imports: false
    prefer_typing_uninitialized_variables: false
    sized_box_for_whitespace: false
    sized_box_shrink_expand: false
    sort_child_properties_last: false
    sort_unnamed_constructors_first: false
    type_annotate_public_apis: false
    unawaited_futures: false
    unnecessary_lambdas: false
    unnecessary_null_checks: false
    unnecessary_nullable_for_final_variable_declarations: false
    unnecessary_raw_strings: false
    unnecessary_to_list_in_spreads: false
    use_build_context_synchronously: false
    use_colored_box: false
    use_decorated_box: false
    use_if_null_to_convert_nulls_to_bools: false
    use_key_in_widget_constructors: false
    use_late_for_private_fields_and_variables: false
    use_setters_to_change_properties: false
    use_string_buffers: false
    use_super_parameters: false